name: aip-project

services:
  app:
    container_name: aip-project
    image: aip-project:1.0.0
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=./tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
      - N_CTX=512
      - N_THREADS=4